version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  my-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
        auth:
          username: flauberjp
          password: $DOCKER_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      #- docker/install-docker
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t flauberjp/udagram-api-feed:$TAG -t flauberjp/udagram-api-feed:latest .
          echo $DOCKER_PASSWORD | docker login -u flauberjp --password-stdin
          docker push flauberjp/udagram-api-feed --all-tags
  update-container-imag: 
    steps:
       - update-kubeconfig-with-authenticator:
          cluster-name: MyEKSCluster
          install-kubectl: true
      - aws-eks/update-container-image:
          cluster-name: MyEKSCluster
          resource-name: deployment/backend-feed
          container-image-updates: "flauberjp/udagram-api-feed=flauberjp/udagram-api-feed:latest"

workflows:
  my-workflow:
    jobs:
      - my-job
      - update-container-imag
